In [1]:
import tensorwrap as tf
tf.__version__

'0.0.0.3'

In [2]:
from tensorwrap import nn

In [3]:
layer = tf.nn.layers.Dense(units = 10)
layer1 = tf.nn.layers.Dense(units = 1)

In [4]:
x = tf.range(1, 101, dtype=tf.float32)
x /= 100
x = tf.expand_dims(x, axis = 1)

In [5]:
model = nn.Sequential([
    layer, 
    layer1
])

In [6]:
model.compile(
    loss = tf.nn.losses.mse,
    optimizer = tf.nn.optimizers.SGD(),
    metrics = tf.nn.losses.mae
)

In [7]:
%timeit model.fit(x, x + 10, epochs = 100)

Epoch 1|100 
[=========================]    Loss:   88.95599     Metric:    9.42594
Epoch 2|100 
[=========================]    Loss:   48.95475     Metric:    6.93035
Epoch 3|100 
[=========================]    Loss:   21.90447     Metric:    4.41309
Epoch 4|100 
[=========================]    Loss:   10.27958     Metric:    2.63902
Epoch 5|100 
[=========================]    Loss:    6.87853     Metric:    2.18450
Epoch 6|100 
[=========================]    Loss:    6.26515     Metric:    2.14273
Epoch 7|100 
[=========================]    Loss:    6.30084     Metric:    2.16778
Epoch 8|100 
[=========================]    Loss:    6.40788     Metric:    2.19088
Epoch 9|100 
[=========================]    Loss:    6.48175     Metric:    2.20460
Epoch 10|100 
[=========================]    Loss:    6.52261     Metric:    2.21166
Epoch 11|100 
[=========================]    Loss:    6.54349     Metric:    2.21537
Epoch 12|100 
[=========================]    Loss:    6.55382     Metric: 

In [8]:
x.shape

(100, 1)

In [9]:
model.layers[1].trainable_variables

[Array([[0.8208539 ],
        [1.22068   ],
        [0.87603647],
        [0.5612704 ],
        [1.1723231 ],
        [0.94479555],
        [0.9512612 ],
        [1.258809  ],
        [0.8402924 ],
        [1.0060971 ]], dtype=float32),
 Array([0.5180042], dtype=float32)]

In [10]:
layer.trainable_variables

[Array([[1.2300738 , 0.89157027, 0.90999573, 1.274644  , 1.0453742 ,
         0.64918023, 1.0918255 , 0.78931564, 1.2479985 , 1.3367093 ]],      dtype=float32),
 Array([0.5180042, 0.5180042, 0.5180042, 0.5180042, 0.5180042, 0.5180042,
        0.5180042, 0.5180042, 0.5180042, 0.5180042], dtype=float32)]

In [11]:
layer1.trainable_variables

[Array([[0.8208539 ],
        [1.22068   ],
        [0.87603647],
        [0.5612704 ],
        [1.1723231 ],
        [0.94479555],
        [0.9512612 ],
        [1.258809  ],
        [0.8402924 ],
        [1.0060971 ]], dtype=float32),
 Array([0.5180042], dtype=float32)]

In [12]:
model.predict([[0.01]])

Array([[5.61675]], dtype=float32)